### ISSUE TITLE
10001 - ROADMAP STATUS OBRAS

### ISSUE THREAD

**Issue by PablofeidlerBM** [PablofeidlerBM/Backlog_Proyectos#2]
- [ ] Tablero en Data Studio o en Excel
- [ ] Ajustar proceso de carga / limitar modificación de cambios
- [ ] Seguimiento de las obras, alerta ante los desvios a AleM
